#! /bin/bash
set -euxo pipefail
IFS=$' '

echo $(PWD)
[ -f ~/.ackrc ] || ln -s $(PWD)/ackrc ~/.ackrc
[ -f ~/.agignore ] || ln -s $(PWD)/agignore ~/.agignore
[ -f ~/.gemrc ] || ln -s $(PWD)/gemrc ~/.gemrc
[ -d ~/.git_template ] || ln -s $(PWD)/git_template ~/.git_template
[ -f ~/.gitconfig ] || ln -s $(PWD)/gitconfig ~/.gitconfig
[ -f ~/.gitignore_global ] || ln -s $(PWD)/gitignore_global ~/.gitignore_global
[ -f ~/.psqlrc ] || ln -s $(PWD)/psqlrc ~/.psqlrc
[ -f ~/.tmux.conf ] || ln -s $(PWD)/tmux.conf ~/.tmux.conf
[ -d ~/.vim ] || ln -s $(PWD)/vim ~/.vim
[ -f ~/.vimrc ] || ln -s $(PWD)/vimrc ~/.vimrc
[ -d ~/.zsh ] || ln -s $(PWD)/zsh ~/.zsh
[ -f ~/.zshrc ] || ln -s $(PWD)/zshrc ~/.zshrc
mkdir -p ~/.config
[ -d ~/.config/nvim ] || ln -s $(PWD)/config/nvim ~/.config/nvim
[ -f ~/.config/starship.toml ] || ln -s $(PWD)/config/starship.toml ~/.config/starship.toml
mkdir -p ~/.gnupg
chmod 755 ~/.gnupg
[ -f ~/.gnupg/gpg.conf ] || ln -s $(PWD)/gnupg/gpg.conf ~/.gnupg/gpg.conf
[ -f ~/.gnupg/gpg-agent.conf ] || ln -s $(PWD)/gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf

echo "🎉 Ready to go"
