#! /bin/bash
set -euxo pipefail
IFS=$' '

echo $(pwd)
[ -f ~/.ackrc ] || ln -s $(pwd)/ackrc ~/.ackrc
[ -f ~/.agignore ] || ln -s $(pwd)/agignore ~/.agignore
[ -d ~/.git_template ] || ln -s $(pwd)/git_template ~/.git_template
[ -f ~/.gitconfig ] || ln -s $(pwd)/gitconfig ~/.gitconfig
[ -f ~/.gitignore_global ] || ln -s $(pwd)/gitignore_global ~/.gitignore_global
[ -f ~/.psqlrc ] || ln -s $(pwd)/psqlrc ~/.psqlrc
[ -f ~/.tmux.conf ] || ln -s $(pwd)/tmux.conf ~/.tmux.conf
[ -d ~/.vim ] || ln -s $(pwd)/vim ~/.vim
[ -f ~/.vimrc ] || ln -s $(pwd)/vimrc ~/.vimrc
[ -d ~/.zsh ] || ln -s $(pwd)/zsh ~/.zsh
[ -f ~/.zshrc ] || ln -s $(pwd)/zshrc ~/.zshrc
mkdir -p ~/.config
[ -d ~/.config/nvim ] || ln -s $(pwd)/config/nvim ~/.config/nvim
[ -f ~/.config/starship.toml ] || ln -s $(pwd)/config/starship.toml ~/.config/starship.toml
mkdir -p ~/.ssh
chmod 755 ~/.ssh
[ -f ~/.ssh/config ] || ln -s $(pwd)/ssh/config ~/.ssh/config
mkdir -p ~/.gnupg
chmod 755 ~/.gnupg
[ -f ~/.gnupg/gpg.conf ] || ln -s $(pwd)/gnupg/gpg.conf ~/.gnupg/gpg.conf
[ -f ~/.gnupg/gpg-agent.conf ] || ln -s $(pwd)/gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf

echo "🎉 Ready to go"
